# Generated by Django 5.2.8 on 2025-11-13 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id_casa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estatus', models.CharField(choices=[('en venta', 'En Venta'), ('vendida', 'Vendida')], default='en venta', max_length=10)),
                ('habitaciones', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True)),
                ('superficie_m2', models.IntegerField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
        migrations.CreateModel(
            name='ImagenCasa',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(help_text='Imagen de la propiedad', upload_to='casas_imagenes/')),
                ('texto_alternativo', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web.casa')),
            ],
            options={
                'verbose_name': 'Imagen de Casa',
                'verbose_name_plural': 'Imágenes de Casas',
                'ordering': ['orden'],
            },
        ),
    ]
