# Generated by Django 4.2.26 on 2025-11-23 00:40

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_casa_banos_alter_casa_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de latitud (-90 a 90) - Se llena automáticamente', max_digits=10, null=True, validators=[web.models.validar_latitud]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de longitud (-180 a 180) - Se llena automáticamente', max_digits=11, null=True, validators=[web.models.validar_longitud]),
        ),
    ]
