# Generated by Django 4.2.26 on 2025-11-23 20:01

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_casa_latitud_alter_casa_longitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterField(
            model_name='casa',
            name='banos',
            field=models.IntegerField(blank=True, help_text='Número de baños (mayor a 0)', null=True, validators=[web.models.validar_banos_positivos]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal de 5 dígitos (ej. 64000)', max_length=10, null=True, validators=[web.models.validar_codigo_postal], verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='direccion',
            field=models.CharField(blank=True, help_text='Calle y número de la propiedad', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='estatus',
            field=models.CharField(choices=[('en venta', 'En Venta'), ('vendida', 'Vendida')], default='en venta', help_text='Estatus actual de la propiedad', max_length=10),
        ),
        migrations.AlterField(
            model_name='casa',
            name='habitaciones',
            field=models.IntegerField(blank=True, help_text='Número de habitaciones (mayor a 0)', null=True, validators=[web.models.validar_habitaciones_positivas]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de latitud (-90 a 90). Se puede llenar desde el mapa o el botón.', max_digits=10, null=True, validators=[web.models.validar_latitud]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de longitud (-180 a 180). Se puede llenar desde el mapa o el botón.', max_digits=11, null=True, validators=[web.models.validar_longitud]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos mexicanos (mayor a 0)', max_digits=10, validators=[web.models.validar_precio_positivo]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='superficie_m2',
            field=models.IntegerField(blank=True, help_text='Superficie en metros cuadrados (mayor a 0)', null=True, validators=[web.models.validar_superficie_positiva]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='titulo',
            field=models.CharField(help_text="Título descriptivo de la propiedad (ej. 'Casa en el centro de Monterrey')", max_length=255),
        ),
        migrations.AlterField(
            model_name='imagenbase',
            name='imagen_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Datos de la imagen'),
        ),
        migrations.AlterField(
            model_name='imagencasa',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden en el carrusel (0, 1, 2, ...)'),
        ),
        migrations.AlterField(
            model_name='imagencasa',
            name='texto_alternativo',
            field=models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='imagencasa',
            unique_together={('casa', 'imagen_base', 'orden')},
        ),
    ]
