# Generated by Django 4.2.26 on 2025-11-23 20:48

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_casa_options_alter_casa_banos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterModelOptions(
            name='imagenbase',
            options={'ordering': ['nombre'], 'verbose_name': 'Imagen de galería', 'verbose_name_plural': 'Imágenes de galería'},
        ),
        migrations.AlterModelOptions(
            name='imagencasa',
            options={'ordering': ['orden'], 'verbose_name': 'Imagen de casa', 'verbose_name_plural': 'Imágenes de casas'},
        ),
        migrations.AlterUniqueTogether(
            name='imagencasa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='casa',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Código postal de 5 dígitos', max_length=10, null=True, validators=[web.models.validar_codigo_postal], verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección completa de la propiedad (calle y número)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='estatus',
            field=models.CharField(choices=[('en venta', 'En Venta'), ('vendida', 'Vendida')], default='en venta', max_length=10),
        ),
        migrations.AlterField(
            model_name='casa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de latitud (-90 a 90). Se puede llenar desde el mapa o automáticamente.', max_digits=10, null=True, validators=[web.models.validar_latitud]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de longitud (-180 a 180). Se puede llenar desde el mapa o automáticamente.', max_digits=11, null=True, validators=[web.models.validar_longitud]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos mexicanos', max_digits=10, validators=[web.models.validar_precio_positivo]),
        ),
        migrations.AlterField(
            model_name='casa',
            name='titulo',
            field=models.CharField(help_text='Título descriptivo de la propiedad', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagenbase',
            name='categoria',
            field=models.CharField(blank=True, help_text='Categoría (exterior, interior, jardín, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagenbase',
            name='tipo_contenido',
            field=models.CharField(blank=True, help_text='Tipo MIME (image/jpeg, image/png, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagencasa',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden en el carrusel de imágenes.'),
        ),
        migrations.AlterField(
            model_name='imagencasa',
            name='texto_alternativo',
            field=models.CharField(blank=True, help_text='Texto alternativo para accesibilidad / SEO.', max_length=100, null=True),
        ),
    ]
